# Markdownlint configuration for geoserver-docker-rhel
# Ignore README.md to avoid conflicts with upstream sync

# Files to ignore
ignores:
  - "README.md"

# Global rule configuration
config:
  # Allow long lines for URLs and code blocks
  MD013:
    line_length: 120
    code_blocks: false
    tables: false
    
  # Allow duplicate headings (common in changelogs)
  MD024:
    siblings_only: true
    
  # Allow inline HTML (useful for badges and formatting)
  MD033: false
  
  # Allow bare URLs (useful for quick references)
  MD034: false
