name: Security Scan

on:
  push:
    branches:
      - master
      - fork
  pull_request:
    branches:
      - master
      - fork
  schedule:
    # Run security scan daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  trivy-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Build Docker image for scanning
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          load: true
          tags: geoserver-security-scan:latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          image-ref: 'geoserver-security-scan:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'  # Don't fail the build on vulnerabilities

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@16140ae1a102900babc80a33c44059580f687047 # v4
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Trivy vulnerability scanner (Table format)
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        continue-on-error: true  # Don't stop workflow on vulnerabilities
        with:
          image-ref: 'geoserver-security-scan:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'  # Fail on critical/high vulnerabilities

      - name: Run Trivy config scanner
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        continue-on-error: true  # Ensure upload steps run even if scan fails
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-config-results.sarif'
          exit-code: '0'

      - name: Upload Trivy config scan results
        uses: github/codeql-action/upload-sarif@16140ae1a102900babc80a33c44059580f687047 # v4
        if: always()
        with:
          sarif_file: 'trivy-config-results.sarif'

      - name: Run Trivy secret scanner
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        continue-on-error: true  # Ensure upload steps run even if scan fails
        with:
          scan-type: 'fs'
          scan-ref: '.'
          scanners: 'secret'
          format: 'sarif'
          output: 'trivy-secret-results.sarif'
          exit-code: '0'

      - name: Upload Trivy secret scan results
        uses: github/codeql-action/upload-sarif@16140ae1a102900babc80a33c44059580f687047 # v4
        if: always()
        with:
          sarif_file: 'trivy-secret-results.sarif'

  # Scan published images from Docker Hub
  scan-published:
    name: Scan Published Images
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    
    strategy:
      matrix:
        tag:
          - latest-ubi9
    
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run Trivy vulnerability scanner on published image
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/geoserver:${{ matrix.tag }}'
          format: 'sarif'
          output: 'trivy-published-${{ matrix.tag }}.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'

      - name: Upload scan results for published image
        uses: github/codeql-action/upload-sarif@16140ae1a102900babc80a33c44059580f687047 # v4
        if: always()
        with:
          sarif_file: 'trivy-published-${{ matrix.tag }}.sarif'
          category: 'published-${{ matrix.tag }}'
